# _config.yml

# Configuración básica de Jekyll
title: "PA3TDD"
description: "Proyecto PA3TDD - Desarrollo de software"
url: "https://EynerSalvador.github.io/PA3TDD"
baseurl: "/PA3TDD" # Base URL para GitHub Pages
author: "EynerSalvador"

# Configuración del repositorio en GitHub
repository: "EynerSalvador/PA3TDD" # Reemplaza con el nombre de tu repositorio
github_username: "EynerSalvador"

# Configuración de los plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Configuración del feed de Jekyll
feed:
  path: /feed.xml

# Permitir la creación de archivos en carpetas dentro de /_posts/
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Configuración de los permalinks
permalink: /:categories/:year/:month/:day/:title/

# Idioma
lang: "es"

# Configuración de SEO
seo:
  title: "PA3TDD - Proyecto Jekyll"
  description: "Sitio personal para el proyecto PA3TDD"
  url: "https://EynerSalvador.github.io/PA3TDD"
  twitter: "@EynerSalvador"

# Configuración para evitar errores al usar Github Pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
