# ===== CONFIGURACIÓN BÁSICA =====
title: Mi Portafolio Profesional
email: tu@email.com
description: >-
  Portafolio profesional desarrollado con Jekyll, implementando TDD y ORM con JSON
baseurl: "" 
url: ""

# ===== CONFIGURACIÓN JEKYLL =====
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
permalink: pretty

# ===== CONFIGURACIÓN ASSETS (CRÍTICA) =====
assets:
  sources:
    - assets
  cache: false # Desactivar en desarrollo

# ===== INCLUSIONES/EXCLUSIONES (ESENCIAL) =====
include:
  - assets/js
  - assets/js/tests  # Nombre exacto de tu carpeta
  - assets/css
  - _data/db.json    # Solo si tus pruebas lo necesitan

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .vscode
  - .github
  - .github/workflows/*.sample

# ===== ENTORNOS =====
development: &development
  url: http://localhost:4000
  assets:
    debug: true

production: &production
  url: https://tudominio.com
  assets:
    debug: false

environments:
  development: *development
  production: *production

# ===== CONFIGURACIÓN PARA JASMINE =====
test_env: &test_env
  url: ""
  baseurl: ""

# ===== CONFIGURACIÓN PERSONALIZADA =====
custom:
  orm:
    debug: true
    base_url: ""

# ===== GITHUB PAGES =====
github:
  repository: username/repo-name
  branch: main

# ===== SEO =====
seo:
  title: true
  description: true
  image: "/assets/images/og-image.jpg"
