name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - main  # O la rama en la que quieras desplegar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.6  # O cualquier versión que estés usando

    - name: Install dependencies
      run: |
        bundle install

    - name: Build the site
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_branch: gh-pages  # La rama de despliegue
        github_token: ${{ secrets.GITHUB_TOKEN }}
